## **Task1 데이터 전처리**

**pilot 프로젝트의 목적**  
1) 스트리밍 수가 높은 음악에는 어떤 특성이 있는지 데이터 분석
2) 추천시스템 (컨텐츠 기반)


1번을 수행하기 위한 데이터 전처리는 week1에서 처리했음!  
-> url처럼 필요 없는 컬럼 제거, stream수가 null인 행을 제거, 공식 영상 여부(official)를 object로 변경  

2번을 수행하기 위해서는 추가적인 데이터셋이 필요함  
-> 청취했던 음악에 대한 호감도를 포함하는 데이터셋이 필요!
   내가 좋아하는 음악에는 어떤 유사성이 있는지, 이와 유사한 음악에는 어떤 것이 있는지 알아야함!  
   
+ 컨텐츠 기반 추천시스템이란? 사용자가 과거에 좋아했던 아이템과 유사한 컨텐츠를 추천

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
my = pd.read_csv("my.csv")

In [10]:
#나의 청취했던 음악 데이터셋을 만들었음!
#my = music.iloc[[41]]
#my = pd.concat([my, music.iloc[[20670]]])
my

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream
0,Coldplay,Viva La Vida,Viva La Vida or Death and All His Friends,album,0.486,0.617,5.0,-7.115,0.0287,0.09540,0.000003,0.1090,0.417,138.015,242373.0,789581468.0,4370461.0,261790.0,True,1.325576e+09
1,Coldplay,A Sky Full of Stars,Ghost Stories,album,0.545,0.675,6.0,-6.474,0.0279,0.00617,0.001970,0.2090,0.162,124.970,267867.0,786404613.0,3741300.0,79974.0,True,1.021782e+09
2,Coldplay,My Universe,Music Of The Spheres,album,0.573,0.711,1.0,-6.268,0.0406,0.01140,0.000000,0.3280,0.470,105.006,226198.0,254655970.0,8867547.0,432726.0,True,8.832242e+08
3,Radiohead,Creep,Pablo Honey,album,0.515,0.430,7.0,-9.935,0.0372,0.00970,0.000133,0.1290,0.104,91.844,238640.0,763497849.0,4777393.0,147276.0,True,1.101855e+09
4,AC/DC,Back In Black,Back In Black,album,0.310,0.700,9.0,-5.678,0.0470,0.01100,0.009650,0.0828,0.763,188.386,255493.0,915158054.0,5643694.0,134549.0,True,1.182379e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,NewJeans,Ditto,Ditto,single,0.814,0.641,6.0,-5.957,0.1110,0.02700,0.000000,0.0993,0.183,133.854,185507.0,24807233.0,1201040.0,32083.0,True,NaN
250,NewJeans,OMG,NewJeans 'OMG',single,0.804,0.771,9.0,-4.067,0.0433,0.35700,0.000003,0.1080,0.739,126.956,212253.0,17909792.0,1150302.0,47572.0,True,NaN
251,NewJeans,Hype Boy,NewJeans 1st EP 'New Jeans',single,0.593,0.935,4.0,-3.430,0.2250,0.26800,0.000000,0.2860,0.783,99.976,179027.0,16744987.0,561759.0,8567.0,True,NaN
252,NewJeans,Attention,NewJeans 1st EP 'New Jeans',single,0.811,0.648,10.0,-3.684,0.0368,0.23600,0.000000,0.0761,0.695,104.988,180067.0,41370607.0,1424462.0,38484.0,True,NaN
253,NewJeans,Cookie,NewJeans 1st EP 'New Jeans',single,0.847,0.638,0.0,-3.764,0.0575,0.05960,0.000000,0.0894,0.661,156.935,235562.0,42190984.0,969125.0,32088.0,True,NaN

In [14]:
my.info()
#stream에 결측치가 있음!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            254 non-null    object
 1   Track             254 non-null    object
 2   Album             254 non-null    object
 3   Album_type        254 non-null    object
 4   Danceability      254 non-null    float64
 5   Energy            254 non-null    float64
 6   Key               254 non-null    float64
 7   Loudness          254 non-null    float64
 8   Speechiness       254 non-null    float64
 9   Acousticness      254 non-null    float64
 10  Instrumentalness  254 non-null    float64
 11  Liveness          254 non-null    float64
 12  Valence           254 non-null    float64
 13  Tempo             254 non-null    float64
 14  Duration_ms       254 non-null    float64
 15  Views             254 non-null    float64
 16  Likes             254 non-null    float64
 17  Comments          254 non-null    float64
 18  official_video    254 non-null    bool
 19  Stream            249 non-null    float64
dtypes: bool(1), float64(15), object(4)
memory usage: 38.1+ KB

In [16]:
#결측치가 있는 행을 알아보겠음!
my[my['Stream'].isnull()]

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream
249,NewJeans,Ditto,Ditto,single,0.814,0.641,6.0,-5.957,0.1110,0.0270,0.000000,0.0993,0.183,133.854,185507.0,24807233.0,1201040.0,32083.0,True,NaN
250,NewJeans,OMG,NewJeans 'OMG',single,0.804,0.771,9.0,-4.067,0.0433,0.3570,0.000003,0.1080,0.739,126.956,212253.0,17909792.0,1150302.0,47572.0,True,NaN
251,NewJeans,Hype Boy,NewJeans 1st EP 'New Jeans',single,0.593,0.935,4.0,-3.430,0.2250,0.2680,0.000000,0.2860,0.783,99.976,179027.0,16744987.0,561759.0,8567.0,True,NaN
252,NewJeans,Attention,NewJeans 1st EP 'New Jeans',single,0.811,0.648,10.0,-3.684,0.0368,0.2360,0.000000,0.0761,0.695,104.988,180067.0,41370607.0,1424462.0,38484.0,True,NaN
253,NewJeans,Cookie,NewJeans 1st EP 'New Jeans',single,0.847,0.638,0.0,-3.764,0.0575,0.0596,0.000000,0.0894,0.661,156.935,235562.0,42190984.0,969125.0,32088.0,True,NaN

stream수에 대한 분석을 할때는 stream수가 중요해서 결측치가 있는 행을 제거했지만 이번 데이테셋에서는 그냥 두겠음  
stream값은 knn이나 회귀로 값을 구할 수 없다고 판단 -> 결측치를 처리할 방법을 생각해야함

측정 시기가 비슷한 다른 데이터셋에서 값을 가져오겠음!    
출처: https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023

In [22]:
my.loc[249, 'Stream'] = 3.97582059e8
my.loc[250, 'Stream'] = 4.30977451e8
my.loc[251, 'Stream'] = 3.63472647e8
my.loc[252, 'Stream'] = 2.6471748e8
my.loc[253, 'Stream'] = 1.00532023e8

In [25]:
my.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            254 non-null    object
 1   Track             254 non-null    object
 2   Album             254 non-null    object
 3   Album_type        254 non-null    object
 4   Danceability      254 non-null    float64
 5   Energy            254 non-null    float64
 6   Key               254 non-null    float64
 7   Loudness          254 non-null    float64
 8   Speechiness       254 non-null    float64
 9   Acousticness      254 non-null    float64
 10  Instrumentalness  254 non-null    float64
 11  Liveness          254 non-null    float64
 12  Valence           254 non-null    float64
 13  Tempo             254 non-null    float64
 14  Duration_ms       254 non-null    float64
 15  Views             254 non-null    float64
 16  Likes             254 non-null    float64
 17  Comments          254 non-null    float64
 18  official_video    254 non-null    bool
 19  Stream            254 non-null    float64
dtypes: bool(1), float64(15), object(4)
memory usage: 38.1+ KB

In [28]:
#이 데이터셋을 my_music으로 저장하겠음
my.to_csv("my_music.csv", index=False)

## **Task2 피쳐 엔지니어링 (Feature Engineering)**

의미 있는 컬럼을 만들어봅시다!  
1. my_music에 socre컬럼을 추가 -> 음악에 대한 호감도를 score를 남김
2. 음악 어플에 기록 되어있는 나의 음악 재생 횟수를 추가 -> 있는 컬럼만

In [79]:
#호감도 컬럼 추가
my_music = pd.read_csv("my_music.csv")

my_music.iloc[240:]

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream
240,(G)I-DLE,Nxde,I love,single,0.726,0.910,4.0,-1.948,0.1790,0.04130,0.000008,0.4790,0.648,135.966,178453.0,171032312.0,2852080.0,107091.0,True,95467384.0
241,(G)I-DLE,TOMBOY,I NEVER DIE,album,0.755,0.870,1.0,-2.414,0.0936,0.00988,0.000000,0.0917,0.645,124.032,174387.0,204797335.0,3023589.0,211850.0,True,148391828.0
242,(G)I-DLE,MY BAG,I NEVER DIE,album,0.838,0.823,8.0,-3.929,0.1640,0.08640,0.000071,0.1560,0.759,94.024,160520.0,58677526.0,951862.0,15988.0,True,65079854.0
243,(G)I-DLE,LION,I trust,single,0.741,0.715,4.0,-5.206,0.0340,0.03180,0.000000,0.1210,0.187,109.989,210973.0,119063352.0,2052120.0,105578.0,True,75894164.0
244,ITZY,SNEAKERS,CHECKMATE,album,0.935,0.849,7.0,-3.047,0.0779,0.01920,0.000000,0.0223,0.551,119.986,179453.0,127399498.0,2274775.0,400111.0,True,58856576.0
245,ITZY,DALLA DALLA,IT'z Different,single,0.790,0.853,11.0,-4.564,0.0666,0.00116,0.000042,0.3290,0.713,125.000,199874.0,312556551.0,4200238.0,339059.0,True,202118613.0
246,IVE,After LIKE,After LIKE,single,0.680,0.922,0.0,-1.215,0.1210,0.10300,0.000000,0.0877,0.799,125.014,176973.0,170808972.0,2446553.0,202177.0,False,166255762.0
247,IVE,LOVE DIVE,LOVE DIVE,single,0.703,0.709,1.0,-4.169,0.0433,0.00379,0.000054,0.3330,0.538,117.941,177187.0,190112394.0,2408257.0,122332.0,False,226258788.0
248,IVE,ELEVEN,ELEVEN,single,0.828,0.731,9.0,-3.033,0.1110,0.06170,0.000000,0.0480,0.587,119.978,178453.0,178904653.0,2611370.0,133665.0,False,202947645.0
249,NewJeans,Ditto,Ditto,single,0.814,0.641,6.0,-5.957,0.1110,0.02700,0.000000,0.0993,0.183,133.854,185507.0,24807233.0,1201040.0,32083.0,True,397582059.0
250,NewJeans,OMG,NewJeans 'OMG',single,0.804,0.771,9.0,-4.067,0.0433,0.35700,0.000003,0.1080,0.739,126.956,212253.0,17909792.0,1150302.0,47572.0,True,430977451.0
251,NewJeans,Hype Boy,NewJeans 1st EP 'New Jeans',single,0.593,0.935,4.0,-3.430,0.2250,0.26800,0.000000,0.2860,0.783,99.976,179027.0,16744987.0,561759.0,8567.0,True,363472647.0
252,NewJeans,Attention,NewJeans 1st EP 'New Jeans',single,0.811,0.648,10.0,-3.684,0.0368,0.23600,0.000000,0.0761,0.695,104.988,180067.0,41370607.0,1424462.0,38484.0,True,264717480.0
253,NewJeans,Cookie,NewJeans 1st EP 'New Jeans',single,0.847,0.638,0.0,-3.764,0.0575,0.05960,0.000000,0.0894,0.661,156.935,235562.0,42190984.0,969125.0,32088.0,True,100532023.0

In [85]:
score = [4, 3, 2, 2, 2, 1, 2, 1, 1, 4, 4, 3, 4, 3, 1, 2, 5, 2, 3, 2, 
        1, 3, 5, 3, 2, 3, 2, 3, 1, 5, 5, 4, 1, 2, 2, 3, 3, 4, 5, 2, 
        2, 1, 1, 1, 3, 1, 5, 2, 5, 3, 4, 1, 1, 1, 1, 1, 1, 5, 3, 3,
        5, 1, 2, 2, 3, 3, 2, 3, 4, 5, 5, 3, 5, 5, 5, 4, 5, 4, 2, 2, 
        1, 1, 1, 5, 3, 4, 5, 5, 3, 3, 1, 1, 1, 2, 2, 1, 2, 1, 3, 1, 
        1, 1, 5, 5, 3, 3, 4, 3, 4, 1, 2, 3, 2, 2, 3, 1, 2, 5, 1, 3, 
        1, 1, 2, 1, 2, 2, 1, 5, 3, 4, 3, 2, 1, 1, 1, 1, 2, 2, 2, 1, 
        2, 3, 1, 2, 1, 2, 2, 3, 2, 5, 3, 4, 4, 3, 4, 5, 5, 3, 1, 2, 
        2, 4, 4, 4, 5, 2, 1, 1, 2, 4, 4, 3, 3, 5, 2, 2, 1, 1, 1, 1,
        1, 4, 2, 3, 3, 2, 3, 2, 2, 3, 5, 2, 3, 1, 3, 3, 2, 3, 5, 5,
        2, 2, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 5, 4, 5, 5, 4, 4, 
        5, 4, 5, 5, 3, 3, 3, 3, 4, 2, 3, 2, 1, 4, 4, 3, 2, 4, 4, 3, 
        3, 3, 1, 4, 2, 1, 1, 1, 1, 3, 3, 4, 4, 3]

my_music['Score'] = score

In [87]:
my_music

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,...,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream,Score
0,Coldplay,Viva La Vida,Viva La Vida or Death and All His Friends,album,0.486,0.617,5.0,-7.115,0.0287,0.09540,...,0.1090,0.417,138.015,242373.0,789581468.0,4370461.0,261790.0,True,1.325576e+09,4
1,Coldplay,A Sky Full of Stars,Ghost Stories,album,0.545,0.675,6.0,-6.474,0.0279,0.00617,...,0.2090,0.162,124.970,267867.0,786404613.0,3741300.0,79974.0,True,1.021782e+09,3
2,Coldplay,My Universe,Music Of The Spheres,album,0.573,0.711,1.0,-6.268,0.0406,0.01140,...,0.3280,0.470,105.006,226198.0,254655970.0,8867547.0,432726.0,True,8.832242e+08,2
3,Radiohead,Creep,Pablo Honey,album,0.515,0.430,7.0,-9.935,0.0372,0.00970,...,0.1290,0.104,91.844,238640.0,763497849.0,4777393.0,147276.0,True,1.101855e+09,2
4,AC/DC,Back In Black,Back In Black,album,0.310,0.700,9.0,-5.678,0.0470,0.01100,...,0.0828,0.763,188.386,255493.0,915158054.0,5643694.0,134549.0,True,1.182379e+09,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,NewJeans,Ditto,Ditto,single,0.814,0.641,6.0,-5.957,0.1110,0.02700,...,0.0993,0.183,133.854,185507.0,24807233.0,1201040.0,32083.0,True,3.975821e+08,3
250,NewJeans,OMG,NewJeans 'OMG',single,0.804,0.771,9.0,-4.067,0.0433,0.35700,...,0.1080,0.739,126.956,212253.0,17909792.0,1150302.0,47572.0,True,4.309775e+08,3
251,NewJeans,Hype Boy,NewJeans 1st EP 'New Jeans',single,0.593,0.935,4.0,-3.430,0.2250,0.26800,...,0.2860,0.783,99.976,179027.0,16744987.0,561759.0,8567.0,True,3.634726e+08,4
252,NewJeans,Attention,NewJeans 1st EP 'New Jeans',single,0.811,0.648,10.0,-3.684,0.0368,0.23600,...,0.0761,0.695,104.988,180067.0,41370607.0,1424462.0,38484.0,True,2.647175e+08,4
253,NewJeans,Cookie,NewJeans 1st EP 'New Jeans',single,0.847,0.638,0.0,-3.764,0.0575,0.05960,...,0.0894,0.661,156.935,235562.0,42190984.0,969125.0,32088.0,True,1.005320e+08,3

In [96]:
#내 음악 어플에 기록되어있는 재생 횟수 컬럼
my_music = my_music.sort_values(by='Score', ascending=False)

In [125]:
my_music.iloc[220:]

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,...,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream,Score
115,Ariana Grande,Stuck with U (with Justin Bieber),Stuck with U,single,0.597,0.450,8.0,-6.658,0.0418,0.22300,...,0.3820,0.537,178.765,228482.0,2.091329e+08,4787585.0,142524.0,True,9.034792e+08,1
56,PSY,I LUV IT,PSY 8th 4X2=8,album,0.874,0.764,5.0,-3.397,0.0488,0.02900,...,0.0407,0.887,124.954,188976.0,1.274299e+08,1152287.0,66770.0,False,1.346834e+07,1
121,IU,Celebrity,IU 5th Album 'LILAC',album,0.730,0.784,9.0,-2.620,0.0691,0.19100,...,0.0956,0.673,99.995,195547.0,1.482368e+08,3252201.0,133211.0,True,1.226318e+08,1
43,TWICE,FANCY,FANCY YOU,single,0.697,0.874,5.0,-2.150,0.0449,0.01220,...,0.6270,0.775,132.018,213880.0,5.652620e+08,6056056.0,766457.0,True,3.688415e+08,1
123,IU,Palette (feat. G-DRAGON),Palette,album,0.804,0.680,0.0,-3.810,0.2000,0.45800,...,0.1020,0.620,102.013,217413.0,1.893966e+08,1740866.0,56759.0,True,1.046074e+08,1
142,BTS,Dynamite,BE,album,0.746,0.765,6.0,-4.410,0.0993,0.01120,...,0.0936,0.737,114.044,199054.0,1.640946e+09,35892575.0,16083138.0,True,1.582446e+09,1
176,EXO,Monster,EX'ACT,album,0.618,0.760,6.0,-4.312,0.0596,0.00660,...,0.1270,0.541,150.000,221341.0,4.278193e+08,5746373.0,1000021.0,True,1.847393e+08,1
193,Red Velvet,Bad Boy,The Perfect Red Velvet - The 2nd Album Repackage,album,0.714,0.736,2.0,-3.801,0.0457,0.19100,...,0.0553,0.814,149.985,210818.0,3.776920e+08,4089347.0,317781.0,True,2.270971e+08,1
126,Imagine Dragons,Thunder,Evolve,album,0.605,0.822,0.0,-4.833,0.0438,0.00671,...,0.1470,0.288,167.997,187147.0,1.936849e+09,11935830.0,363701.0,True,1.900081e+09,1
178,EXO,Growl,The 1st Album 'XOXO' (Repackage),album,0.681,0.814,11.0,-2.830,0.0603,0.14500,...,0.5560,0.876,89.993,207053.0,2.884684e+08,3017243.0,254274.0,True,9.548391e+07,1
177,EXO,CALL ME BABY,EXODUS - The 2nd Album,album,0.692,0.886,1.0,-2.519,0.0519,0.28400,...,0.3410,0.879,100.030,211013.0,3.193630e+08,3752752.0,334270.0,True,1.280386e+08,1
132,Justin Bieber,STAY (with Justin Bieber),F*CK LOVE 3+: OVER YOU,album,0.591,0.764,1.0,-5.484,0.0483,0.03830,...,0.1030,0.478,169.928,141806.0,6.812056e+08,10131328.0,247007.0,True,2.365778e+09,1
133,Justin Bieber,Ghost,Justice,album,0.601,0.741,2.0,-5.569,0.0478,0.18500,...,0.4150,0.441,153.960,153190.0,2.245797e+08,2888687.0,99758.0,True,9.413727e+08,1
134,Justin Bieber,Peaches (feat. Daniel Caesar & Giveon),Justice,album,0.677,0.696,0.0,-6.181,0.1190,0.32100,...,0.4200,0.464,90.030,198082.0,6.189198e+08,7638701.0,230639.0,True,1.335839e+09,1
135,Justin Bieber,Love Yourself,Purpose (Deluxe),album,0.609,0.378,4.0,-9.828,0.4380,0.83500,...,0.2800,0.515,100.418,233720.0,2.731750e+05,5121.0,153.0,False,1.975867e+09,1
179,EXO,Ko Ko Bop,THE WAR - The 4th Album,album,0.749,0.850,0.0,-4.346,0.0468,0.03190,...,0.0678,0.672,145.983,190423.0,3.426554e+08,5163914.0,1058574.0,True,1.558569e+08,1
118,IU,LILAC,IU 5th Album 'LILAC',album,0.738,0.890,2.0,-2.275,0.0748,0.08950,...,0.2130,0.750,114.942,214253.0,9.498555e+07,2346475.0,81368.0,True,1.309292e+08,1
109,Lady Gaga,Poker Face,The Fame,album,0.851,0.806,4.0,-4.620,0.0787,0.11800,...,0.1210,0.787,118.999,237200.0,1.095355e+09,6103722.0,276401.0,True,8.527501e+08,1
120,IU,Blueming,Love poem,single,0.819,0.674,0.0,-3.145,0.0587,0.08490,...,0.0667,0.682,106.032,217053.0,1.564197e+08,2237886.0,47680.0,True,1.090961e+08,1
180,EXO,Tempo,DON’T MESS UP MY TEMPO – The 5th Album,album,0.686,0.842,0.0,-4.423,0.1000,0.23700,...,0.0683,0.519,115.944,224483.0,2.256990e+08,4760999.0,1091235.0,True,1.233168e+08,1
144,BTS,Butter,Proof,album,0.759,0.459,8.0,-5.187,0.0948,0.00323,...,0.0788,0.695,109.997,164952.0,8.503297e+08,22723127.0,9131761.0,True,1.066002e+09,1
204,BLACKPINK,Shut Down,BORN PINK,album,0.818,0.690,0.0,-5.119,0.0454,0.00327,...,0.1860,0.688,110.071,175889.0,3.367361e+08,9638123.0,1756950.0,True,2.955101e+08,1
205,BLACKPINK,Pink Venom,BORN PINK,album,0.693,0.734,4.0,-6.189,0.2020,0.01450,...,0.2170,0.708,180.060,186964.0,5.306304e+08,14969274.0,3637659.0,True,3.868067e+08,1
206,BLACKPINK,As If It's Your Last,As If It's Your Last,single,0.786,0.852,8.0,-2.687,0.0813,0.06870,...,0.0759,0.455,125.036,213264.0,1.246371e+09,12653119.0,1655545.0,True,4.356564e+08,1
158,Troye Sivan,Strawberries & Cigarettes,Strawberries & Cigarettes,single,0.578,0.537,9.0,-8.676,0.0832,0.16200,...,0.0760,0.250,83.909,201539.0,7.482210e+07,652947.0,2252.0,True,4.877111e+08,1
208,BLACKPINK,BOOMBAYAH,SQUARE ONE,single,0.661,0.836,5.0,-3.164,0.0590,0.00268,...,0.4970,0.396,124.952,240793.0,1.532198e+09,15390062.0,1106942.0,True,4.141734e+08,1
209,BLACKPINK,Kill This Love,KILL THIS LOVE,single,0.763,0.835,2.0,-5.234,0.1910,0.32300,...,0.2250,0.645,131.875,191050.0,1.734794e+09,24061574.0,2466445.0,True,6.617903e+08,1
210,BLACKPINK,PLAYING WITH FIRE,SQUARE TWO,single,0.706,0.756,4.0,-4.405,0.0845,0.03920,...,0.1800,0.676,97.098,197289.0,8.032986e+08,8283995.0,532913.0,True,3.202249e+08,1
211,BLACKPINK,DDU-DU DDU-DU,SQUARE UP,single,0.668,0.828,4.0,-5.034,0.0739,0.03600,...,0.0932,0.393,140.042,211350.0,2.012855e+09,22570280.0,3312226.0,True,5.657543e+08,1
28,Disney,Be Our Guest,Beauty And The Beast (Special Edition),compilation,0.435,0.391,2.0,-13.062,0.1620,0.81400,...,0.0885,0.583,73.531,224920.0,4.733999e+07,105691.0,0.0,False,1.178092e+08,1
20,Frank Sinatra,My Way,My Way (Expanded Edition),album,0.401,0.381,2.0,-7.458,0.0274,0.70000,...,0.1220,0.229,75.454,276800.0,4.035649e+07,323576.0,12901.0,True,3.293702e+08,1
14,ABBA,Gimme! Gimme! Gimme! (A Man After Midnight),Voulez-Vous,album,0.749,0.491,10.0,-9.655,0.0403,0.02000,...,0.1590,0.536,119.528,292613.0,3.612881e+08,3156029.0,67741.0,True,5.191843e+08,1
45,TWICE,I CAN'T STOP ME,Eyes Wide Open,album,0.657,0.880,10.0,-3.672,0.1020,0.12100,...,0.4630,0.769,150.084,205493.0,4.776716e+08,6364962.0,2316223.0,True,2.961659e+08,1
207,BLACKPINK,How You Like That,THE ALBUM,album,0.812,0.761,11.0,-5.222,0.0812,0.04650,...,0.0601,0.344,130.032,182956.0,1.182611e+09,24290306.0,5130725.0,True,7.332138e+08,1

In [127]:
list = [0, 0, 278, 157, 96, 0, 45, 144, 45, 265, 65, 40, 0, 0, 205, 157, 81, 0, 0, 79,
       69, 56, 72, 40, 0, 306, 299, 0, 75, 0, 133, 120, 107, 47, 83, 0, 0, 80, 0, 73,
       0, 0, 0, 108, 44, 0, 122, 128, 0, 44, 134, 37, 180, 143, 0, 112, 134, 189, 0, 70,
       74, 65, 0, 0, 58, 62, 0, 39, 229, 95, 95, 0, 184, 147, 38, 41, 154, 71, 0, 0,
       0, 0, 181, 154, 0, 70, 0, 0, 0, 70, 86, 221, 113, 108, 72, 53, 0, 0, 149, 271,
       118, 167, 0, 307, 65, 105, 90, 0, 58, 118, 0, 77, 39, 0, 40, 165, 0, 0, 0, 0,
       76, 0, 0, 0, 0, 231, 0, 0, 41, 0, 61, 0, 37, 0, 0, 0, 0, 0, 0, 69,
       0, 0, 0, 85, 0, 0, 0, 109, 0, 0, 0, 0, 0, 168, 48, 124, 0, 0, 0, 0, 
       0, 70, 0, 0, 0, 0, 0, 0, 0, 0, 75, 0, 73, 0, 0, 0, 110, 0, 0, 190,
       88, 95, 39, 0, 0, 233, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0,0,0,0,0,0,0,0,0,0,0,58,0,87,160,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]

my_music['Count'] = list

In [129]:
my_music

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,...,Valence,Tempo,Duration_ms,Views,Likes,Comments,official_video,Stream,Score,Count
127,Bruno Mars,When I Was Your Man,Unorthodox Jukebox,album,0.612,0.280,0.0,-8.648,0.0434,0.93200,...,0.387,72.795,213827.0,1.237507e+09,6771190.0,193121.0,True,1.439567e+09,5,0
74,Miley Cyrus,Flowers,Flowers,single,0.707,0.681,0.0,-4.325,0.0668,0.06320,...,0.646,117.999,200455.0,1.545193e+08,4625162.0,117998.0,True,2.838849e+08,5,0
57,Maroon 5,Memories,JORDI (Deluxe),album,0.775,0.327,11.0,-7.241,0.0557,0.84100,...,0.595,91.050,189486.0,9.018294e+08,9050321.0,265339.0,True,1.651773e+09,5,278
30,Mariah Carey,All I Want for Christmas Is You,Merry Christmas,album,0.336,0.627,7.0,-7.463,0.0384,0.16400,...,0.350,150.273,241107.0,7.532190e+08,3874002.0,249083.0,True,1.437978e+09,5,157
156,The Weeknd,Blinding Lights,After Hours,album,0.514,0.730,1.0,-5.934,0.0598,0.00146,...,0.334,171.005,200040.0,6.741645e+08,8817927.0,282589.0,True,3.386520e+09,5,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,Disney,Be Our Guest,Beauty And The Beast (Special Edition),compilation,0.435,0.391,2.0,-13.062,0.1620,0.81400,...,0.583,73.531,224920.0,4.733999e+07,105691.0,0.0,False,1.178092e+08,1,0
20,Frank Sinatra,My Way,My Way (Expanded Edition),album,0.401,0.381,2.0,-7.458,0.0274,0.70000,...,0.229,75.454,276800.0,4.035649e+07,323576.0,12901.0,True,3.293702e+08,1,0
14,ABBA,Gimme! Gimme! Gimme! (A Man After Midnight),Voulez-Vous,album,0.749,0.491,10.0,-9.655,0.0403,0.02000,...,0.536,119.528,292613.0,3.612881e+08,3156029.0,67741.0,True,5.191843e+08,1,0
45,TWICE,I CAN'T STOP ME,Eyes Wide Open,album,0.657,0.880,10.0,-3.672,0.1020,0.12100,...,0.769,150.084,205493.0,4.776716e+08,6364962.0,2316223.0,True,2.961659e+08,1,0
207,BLACKPINK,How You Like That,THE ALBUM,album,0.812,0.761,11.0,-5.222,0.0812,0.04650,...,0.344,130.032,182956.0,1.182611e+09,24290306.0,5130725.0,True,7.332138e+08,1,0

In [132]:
my_music.to_csv("my_data.csv", index=False)

#나의 음악 데이터셋에 있는 데이터를 제외한 데이터셋 만들기 
new_music = music[~music['Track'].isin(my_data['Track'])]

music.csv로 저장!

**최종 데이터셋**
1) 분석 데이터셋 -> Spotify_Youtube.csv (pilot 1에서 전처리함)  
2) 추천시스템 데이터셋 -> my_data(내 음악), music(my_data에 있는 데이터 제외)

1)에서는 Stream컬럼을 기준으로 분석, 모데링 진행    
2)에서는 my_data로 학습 후 music데이터셋에 적용!